### ISSUE TITLE
checkNetworkQualityCatchAllConfiguration Triggers on Second Page Instead of First

### ISSUE THREAD

**Issue by rougegoat** [dan-snelson/Setup-Your-Mac#56] opened 2023-05-10 21:53 UTC
> Before submitting a **Setup Your Mac** bug report, please review the [open swiftDialog issues](https://github.com/bartreardon/swiftDialog/issues) to help determine the source of the issue.

**Describe the bug**
The download estimate for the Catch-All configuration runs on the second page, which results in it wiping out all the displayed information like Computer Name, Username, Department, etc in the infobox.

**To Reproduce**
Set `promptForConfiguration` to `false` and `configurationDownloadEstimation` to `true`.  Run as normal.
 
**Expected behavior**
On the first page, you should see the download estimate show in the Infobox section for the catch-all configuration in the same way it works if `promptForConfiguration` is set to `true`.

**Code/log output**
Please supply the full command used, and if applicable, add full output from Terminal. Either upload the log, or paste the output in a code block (triple backticks at the start and end of the code block, please!).

**Screenshots**
These two screenshots have the same User Input entered save for the configuration, which is `Required` on the first and the `Catch-All` on the second.
Screenshot of behavior if `promptForConfiguration` and `configurationDownloadEstimation` are both set to `true`
![Screenshot 2023-05-10 at 4 49 01 PM](https://github.com/dan-snelson/Setup-Your-Mac/assets/541022/17b2b5be-0882-4d0a-a8ce-f0072bc9e0be)

Screenshot of behavior if `promptForConfiguration` is set to `false` and `configurationDownloadEstimation` is set to `true`
![Screenshot 2023-05-10 at 4 41 19 PM](https://github.com/dan-snelson/Setup-Your-Mac/assets/541022/05d8c0ed-9aaf-43f9-a927-065ea6f7e652)

**Environment (please complete the following information):**
 - OS version (i.e., 13.1)  13.3.1 (a)
 - Script version (i.e., 1.6.0) - 1.10.0

**Additional context**
I'm not sure the best route to addressing this.  I think you could potentially combine both the `checkNetworkQualityConfigruation` and `checkNetworkQualityCatchAllConfiguration`, but those interact with enough things that I'm not confident in that guess.

**Comment by dan-snelson** [comment] 2023-05-10 21:57
To me, @rougegoat, this is (currently) "working as designed," but let me replicate and review.

(If there's only a single Configuration, the Dynamic Download Estimates are just an FYI.)

**Comment by dan-snelson** [comment] 2023-05-11 00:13
@rougegoat:

Here's what I'm seeing:

https://github.com/dan-snelson/Setup-Your-Mac/assets/24623109/ed72356c-e479-40c5-9e50-dac4d102cc13

(To me, what happens at `00:15` to `00:16` is a distraction; I'll take a look at removing that.)

**Comment by dan-snelson** [comment] 2023-05-11 00:46
@rougegoat:

The visual "glitch" has been addressed in [`1.10.1-b3`](https://github.com/dan-snelson/Setup-Your-Mac/blob/1.10.1/Setup-Your-Mac-via-Dialog.bash).

(Please feel free to respond here or DM me on the MacAdmins Slack if you'd like to discuss the current approach.)

**Comment by rougegoat** [comment] 2023-05-11 15:20
That half works.  It addresses one issue, but then makes the infobox be stuck as `Analyzing Input...` if `promptForConfiguration` and `configurationDownloadEstimation` are both set to `False`.  That could be addressed by changing line 2895 to 

`if [[ "${promptForConfiguration}" != "true" ]] && [[ "${configurationDownloadEstimation}" == "true" ]]; then`

I think I have a slight rewrite that basically moves the `if [[ "${promptForConfiguration" == "true" ]]; then` bit into the `checkNetworkQualityConfiguration` function.  That makes it so that one function can do both in the same place and removes the need for `checkNetworkQualityCatchAllConfiguration` and other workarounds.  I'll submit a PR.

**Comment by dan-snelson** [comment] 2023-05-12 18:42
Greetings, @rougegoat!

I'll mark this issue "on-hold" while we iron-out #57.

Thanks.

**Comment by dan-snelson** [comment] 2023-05-16 17:32
Since #57 was just closed, closing this as well.

**Closed by dan-snelson** 2023-05-16 17:32 UTC
Labels: enhancement, waiting feedback, on-hold
